---
title: "How does a traffic changes with the school run?"
format: gfm
---


```{r}
options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("remotes")) {
  install.packages("remotes")
}
pkgs = c(
  "sf",
  "tidyverse",
  "tmap",
  "paletteer",
  "remotes"
)
remotes::install_cran(pkgs)
sapply(pkgs, require, character.only = TRUE)
```

Installing and loading telraamR from GitHub if not installed
```{r}
if (!require("telraamR", quietly = T)) {
  install_github("juanfonsecaLS1/telraamR")
}
require("telraamR")
```

Identifying the sensor to explore
```{r}
id <- 9000009334
```

Downloading data

```{r}
data <- read_telraam_traffic(id,
  time_start = "2025-08-15 07:00:00",
  time_end = "2025-09-26 07:00:00",
  report = "per-hour",
  include_speed = TRUE
)
```


```{r}
data_long <- data |> 
    select(datetime,day,hr,car,starts_with("car speed")) |> 
    pivot_longer(cols = starts_with("car speed"),
    names_to = "band",
    values_to = "portion",names_prefix = "car speed  ") |> 
        mutate(portion = portion * 0.01) 
```
```{r}
bands <- tibble(band = unique(data_long$band)) |> 
    mutate(init_value = band |>
     str_extract("(\\[?)\\d{1,3}") |>
      str_remove("\\[") |>
       as.numeric()) |> 
  mutate(init_value = init_value + 2.5) |> 
       arrange(init_value)
```


```{r}
data_long_2 <- data_long |> 
    mutate(band = factor(band,
    levels = bands$band,ordered = TRUE),
    value = portion * car) |> 
  left_join(bands,by = "band") |> 
  summarise(mean = exp(weighted.mean(log(init_value), portion)),
            .by = c(datetime,day,hr)) |> 
  mutate(date = date(datetime),
         school_term = date >= as.Date("2025-09-01"),
         shape = day <= 5)
```

Average speeds 

```{r}
data_long_2 |> 
  filter(abs(hr - 8)<1) |> 
  ggplot(aes(shape,mean,col = school_term))+
  geom_jitter(alpha = 0.3)+
  geom_boxplot(fill = NA,outlier.shape = NA)+
  theme_minimal()+
  labs(x = "weekday")
```

Max speeds

```{r}
data_long |> 
  filter(portion != 0) |> 
    mutate(band = factor(band,
    levels = bands$band,ordered = TRUE),
    value = portion * car) |> 
  left_join(bands,by = "band") |> 
  mutate(date = date(datetime),
         school_term = date >= as.Date("2025-09-01"),
         shape = day <= 5) |> 
  summarise(max_spd = max(init_value),.by = c(date,day,hr,school_term,shape)) |>
  filter(abs(hr - 8)<1) |> 
  ggplot(aes(shape,max_spd,col = school_term))+
  geom_jitter(alpha = 0.3)+
  geom_hline(yintercept = 32,col = "red",linetype = "dashed")+
  geom_boxplot(fill = NA,outlier.shape = NA)+
  theme_minimal()+ 
  labs(x = "weekday")
```

